package com.example.network

import android.util.Log
import okhttp3.OkHttpClient
import okhttp3.Request
import java.net.URLDecoder
import java.util.regex.Pattern

object YoutubeScraper {
    private const val TAG = "YoutubeScraper"
    private val client = OkHttpClient.Builder()
        .followRedirects(true)
        .build()

    data class CaptionTrack(
        val baseUrl: String,
        val languageCode: String,
        val label: String,
        val isAutoGenerated: Boolean
    )

    fun extractVideoId(url: String): String? {
        val pattern = "(?:v=|^\\/embed\\/|^\\/1\\/|^\\/v\\/|https?:\\/\\/youtu\\.be\\/|\\/shorts\\/|\\/embed\\/|watch\\?v=)([^\"&?\\/\\s]{11})"
        val compiledPattern = Pattern.compile(pattern)
        val matcher = compiledPattern.matcher(url)
        return if (matcher.find()) {
            matcher.group(1)
        } else {
            // Fallback for simple raw 11 char copy-paste
            val trimmed = url.trim()
            if (trimmed.length == 11 && !trimmed.contains(" ") && !trimmed.contains("/")) trimmed else null
        }
    }

    suspend fun fetchSrv3Subtitles(videoUrl: String, preferredLang: String = "ar"): String? {
        val videoId = extractVideoId(videoUrl) ?: return null
        Log.d(TAG, "Extracted Video ID: $videoId")
        
        val watchUrl = "https://www.youtube.com/watch?v=$videoId"
        val request = Request.Builder()
            .url(watchUrl)
            .addHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36")
            .addHeader("Accept-Language", "en-US,en;q=0.9")
            .build()

        try {
            val response = client.newCall(request).execute()
            if (!response.isSuccessful) {
                Log.e(TAG, "Unsuccessful watch page response: ${response.code}")
                return null
            }
            val html = response.body?.string() ?: return null
            val tracks = parseCaptionTracks(html)
            if (tracks.isEmpty()) {
                Log.e(TAG, "No caption tracks found in HTML.")
                return null
            }

            // Look for preferred language
            // 1. Exact non-auto-generated preferred lang (e.g. ar)
            // 2. Auto-generated preferred lang
            // 3. Any non-auto-generated lang (e.g. en)
            // 4. Any auto-generated lang
            val selectedTrack = tracks.firstOrNull { it.languageCode == preferredLang && !it.isAutoGenerated }
                ?: tracks.firstOrNull { it.languageCode == preferredLang }
                ?: tracks.firstOrNull { !it.isAutoGenerated }
                ?: tracks.first()

            Log.d(TAG, "Selected subtitle track: languageCode=${selectedTrack.languageCode}, label=${selectedTrack.label}, autoGen=${selectedTrack.isAutoGenerated}")

            // Append fmt=srv3 to obtain the srv3 XML
            var srv3Url = selectedTrack.baseUrl
            if (!srv3Url.contains("fmt=srv3")) {
                srv3Url += if (srv3Url.contains("?")) "&fmt=srv3" else "?fmt=srv3"
            }

            val subtitleRequest = Request.Builder()
                .url(srv3Url)
                .addHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36")
                .build()

            val subResponse = client.newCall(subtitleRequest).execute()
            if (!subResponse.isSuccessful) {
                Log.e(TAG, "Failed to download subtitle content: ${subResponse.code}")
                return null
            }

            return subResponse.body?.string()
        } catch (e: Exception) {
            Log.e(TAG, "Exception during fetchSrv3Subtitles", e)
            return null
        }
    }

    private fun parseCaptionTracks(html: String): List<CaptionTrack> {
        val tracks = mutableListOf<CaptionTrack>()
        val index = html.indexOf("\"captionTracks\"")
        if (index == -1) return emptyList()

        val startIndex = html.indexOf("[", index)
        if (startIndex == -1) return emptyList()

        // Track opening and closing brackets to extract the exact JSON array
        var bracketCount = 1
        var endIndex = startIndex + 1
        while (endIndex < html.length && bracketCount > 0) {
            val char = html[endIndex]
            if (char == '[') bracketCount++
            else if (char == ']') bracketCount--
            endIndex++
        }
        if (bracketCount > 0) return emptyList() // mismatched structure

        val jsonArrayStr = html.substring(startIndex, endIndex)
        
        // Parse individual captions inside the array [{}, {}, ...] using regex
        val objectPattern = Pattern.compile("\\{[^{}]*?}")
        val matcher = objectPattern.matcher(jsonArrayStr)
        while (matcher.find()) {
            val element = matcher.group()
            val baseUrl = extractJsonField(element, "baseUrl") ?: continue
            val decodedUrl = decodeJsonUrl(baseUrl)
            val languageCode = extractJsonField(element, "languageCode") ?: "unknown"
            
            // Extract label/name simpleText
            val nameIndex = element.indexOf("\"name\"")
            var label = "Language"
            if (nameIndex != -1) {
                val labelText = extractJsonField(element.substring(nameIndex), "simpleText")
                if (labelText != null) label = labelText
            }

            val vssId = extractJsonField(element, "vssId") ?: ""
            val isAutoGenerated = vssId.startsWith("a.") || element.contains("\"kind\":\"asr\"") || element.contains("\"kind\":\"asr\"")

            tracks.add(CaptionTrack(decodedUrl, languageCode, label, isAutoGenerated))
        }

        return tracks
    }

    private fun extractJsonField(jsonObjStr: String, fieldName: String): String? {
        val pattern = Pattern.compile("\"$fieldName\"\\s*:\\s*\"([^\"]*?)\"")
        val matcher = pattern.matcher(jsonObjStr)
        return if (matcher.find()) {
            matcher.group(1)
        } else {
            null
        }
    }

    private fun decodeJsonUrl(rawUrl: String): String {
        return try {
            // Replace JSON unicode escapes \\u0026 -> &
            var url = rawUrl.replace("\\u0026", "&")
            url = url.replace("\\u002f", "/")
            url = url.replace("\\", "")
            url
        } catch (e: Exception) {
            rawUrl
        }
    }
}
